# Generated by Django 5.2.5 on 2025-08-27 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('citations', models.JSONField(default=list)),
                ('tools_used', models.JSONField(default=list)),
                ('retrieval_used', models.BooleanField(default=False)),
                ('duration_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
